### ISSUE TITLE
error when building flake that services.k3s.clusterInit does not exist

### ISSUE THREAD

**Issue by prabhu-madanagopal** [mynixos/support#4]
Hi 
I am trying to build nixos iso to run k3s server. I get the below error, could you please help? 
Not sure how a config cannot exist when it was added from selection.
Link to flake: https://mynixos.com/prabhu-madanagopal/k3s-server/versions
Both k3s-server-init and k3s-server-join have the same issue.

error: The option `services.k3s.clusterInit' does not exist. Definition values:
       - In `/nix/store/df79ddi5pqfnp3sawgvip4liyz75hi3i-source/flake.nix': false

**Comment by pveierland** [comment]
It appears that the lockfile for `nixos-generators` is severely outdated, causing your output to be evaluated with a `nixpkgs` version which does not have the `services.k3s.clusterInit` option. Adding a follow from the flake inputs screen from `nixos-generators/nixpkgs` to `nixpkgs`, then re-releasing the flake, should resolve the issue.

**Comment by prabhu-madanagopal** [comment]
Updated inputs and added follow but still failing.
https://mynixos.com/prabhu-madanagopal/k3s-server/inputs

**Comment by pveierland** [comment]
Version 2 of the flake you have linked appears to have the correct follow set up, however no build has been attempted for this version. I'd recommend performing a build action on version 2 of this flake.

**Comment by prabhu-madanagopal** [comment]
Thx, it worked! I had dismissed actions earlier not sure if that's why you did not see the attempted build that had failed, but it works now after I did one more release and build. Thank you.
